server:
  port: 8088
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service-client
          uri: lb://service-client
          predicates:
            - Path=/**
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    eureka-server-port: 8761
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "gateway"
#  endpoint:
#    gateway:
#      enabled: true # default:true